### ISSUE TITLE
Design (social-network)

### ISSUE THREAD

**Issue by nattikim** [merpw/forum#101]
Mockups

# Me
<img width="1412" alt="Screen Shot 2023-08-06 at 17 48 05" src="https://github.com/merpw/forum/assets/93912586/457f6099-c03e-4d92-a9ea-b3551084ac58">

# Group
<img width="1409" alt="Screen Shot 2023-08-06 at 17 45 45" src="https://github.com/merpw/forum/assets/93912586/c6b7ae00-7947-4c55-a6b8-6354922bf97d">
<img width="1397" alt="Screen Shot 2023-08-06 at 20 23 08" src="https://github.com/merpw/forum/assets/93912586/67342d89-760b-4d58-add4-f964d126546d">

# Notification
<img width="1414" alt="Screen Shot 2023-08-06 at 03 32 16" src="https://github.com/merpw/forum/assets/93912586/a3c64bf0-0ca9-4d3d-b435-f483aba252d5">

**Comment by nattikim** [comment]
# Group page 

Group card mockup
<img width="986" alt="Screen Shot 2023-08-05 at 19 28 50" src="https://github.com/merpw/forum/assets/93912586/284a9dca-5e1a-4eb6-8d3b-0fd3038def96">

**Comment by nattikim** [comment]
# Notifications

Notification list mockup

<img width="500
" alt="Screen Shot 2023-08-06 at 01 28 22" src="https://github.com/merpw/forum/assets/93912586/3fd6ee34-394e-4229-955a-862f13c30072">

**Comment by nattikim** [comment]
### Group icons
@maximihajlov I can choose one


<img width="100" alt="Screenshot 2023-08-09 at 18 17 05" src="https://github.com/merpw/forum/assets/93912586/f1931b1a-b351-44e4-a8d5-105fc76c60f6"> <img width="100" alt="Screenshot 2023-08-09 at 18 17 55" src="https://github.com/merpw/forum/assets/93912586/87d2ec90-8846-4205-8b23-f6497a9b38f9"> <img width="100" alt="Screenshot 2023-08-09 at 18 18 01" src="https://github.com/merpw/forum/assets/93912586/ab5a7442-5e34-45e7-b149-91aef5049c88">

**Comment by maximihajlov** [comment]
And how about icons for the `Join`, `Cancel request` and `Leave` buttons?

**Comment by maximihajlov** [comment]
Groups design (#103). Any comments?

![image](https://github.com/merpw/forum/assets/43277901/a7922dba-83f2-455c-aa44-c4e0e6cd2bc5)

**Comment by nattikim** [comment]
@maximihajlov LGTM 👍🏻 Maybe icons in group list are a bit too big... and its border should be bit more rounded

**Comment by maximihajlov** [comment]
> Maybe icons in group list are a bit too big... and its border should be bit more rounded

![image](https://github.com/merpw/forum/assets/43277901/aa129a99-c31d-4dd5-9749-2045dcb00ece)

**Comment by bomanviktor** [comment]
> # Notification
> <img alt="Screen Shot 2023-08-06 at 03 32 16" width="1414" src="https://user-images.githubusercontent.com/93912586/258613809-a3c64bf0-0ca9-4d3d-b435-f483aba252d5.png">

Maybe not smiley faces for the icons, simple `Confirm` and `Delete` would do:
![image](https://github.com/merpw/forum/assets/72476579/ba60fd87-b40c-4b1f-bdd4-1742aca83f50)

**Comment by bomanviktor** [comment]
I found a small issue with comments, posts etc:

![image](https://github.com/merpw/forum/assets/72476579/427a3b49-0d86-4d30-8a8e-db4409b0084a)

We should make the minimum size of the `textArea` bigger, so that the send button is never outside of the element.
@nattikim, @maximihajlov

**Comment by bomanviktor** [comment]
The mockups look absolutely insane by the way! Soooo good!!

**Comment by maximihajlov** [comment]
Oops...

![Screenshot_2023-08-12-17-54-38-77_40deb401b9ffe8e1df2f1cc5ba480b12~2](https://github.com/merpw/forum/assets/43277901/aa9a6a13-d280-4117-97b0-6472d8b9302b)

**Comment by bomanviktor** [comment]
![image](https://github.com/merpw/forum/assets/72476579/90fdf7e4-9362-4461-ad40-37aaebf5f92e)

I got this bug while surfing forum-ci.mer.pw

**Comment by bomanviktor** [comment]
Also for the mockups, I would keep the bell as it's synonymous with notifications. The three dots is more of a settings icon.

**Comment by bomanviktor** [comment]
Another thing, apparently on smaller devices, width is not fixed so you are able to scroll horizontally

**Comment by bomanviktor** [comment]
https://github.com/merpw/forum/pull/104#issuecomment-1670063812

I forgot to put this here.

**Comment by maximihajlov** [comment]
A few problems with groups design. SelectUsers works in a weird way for big amount of users

![image](https://github.com/merpw/forum/assets/43277901/5fda41b4-1497-4ad0-8a4a-d468cb0a0d46)

The button is on the wrong side for group post creation

![image](https://github.com/merpw/forum/assets/43277901/deb59cad-99fe-4c55-aee2-993abda9afb7)

**Comment by bomanviktor** [comment]
Last design issues:

- [ ] Send button on comments and chats are still going outside of the textArea when made smaller:
<img width="204" alt="Screenshot 2023-08-17 at 19 20 43" src="https://github.com/merpw/forum/assets/72476579/52c07d9d-5df9-4e5b-8f77-18da4fe42d77">

- [ ] Privacy switch is still unintuitive. Should either have an icon (lock, unlock), and make it more contrasted. Maybe add confirmation popup: 
<img width="204" alt="Screenshot 2023-08-17 at 19 21 41" src="https://github.com/merpw/forum/assets/72476579/f7612138-f65d-4b6a-992e-fe1005c546d5">

- [ ] Buttons should switch places for accepting events. And add different colors as with the notifications:

<img width="734" alt="Screenshot 2023-08-17 at 19 24 03" src="https://github.com/merpw/forum/assets/72476579/331473c3-6819-4a35-9b69-64d8febcc591">
<img width="305" alt="Screenshot 2023-08-17 at 19 24 50" src="https://github.com/merpw/forum/assets/72476579/e2436b18-be6f-4fef-b891-c9876a8f1e73">

- [ ] More margin is needed between the users in the `Your followers` and `Users you follow`:

<img width="513" alt="Screenshot 2023-08-17 at 19 25 19" src="https://github.com/merpw/forum/assets/72476579/86b8cc8b-ea6d-49f0-b310-ee944cfb0c48">
