### ISSUE TITLE
Fix golangci-lint

### ISSUE THREAD

**Issue by healingdrawing** [merpw/forum#28]
run golangci-lint
  Running [/home/runner/golangci-lint-1.52.2-linux-amd64/golangci-lint run --out-format=github-actions --path-prefix=backend] in [/home/runner/work/forum/forum/backend] ...
  Error: SA5011: possible nil pointer dereference (staticcheck)
  Error: SA5011(related information): this check suggests that the pointer can be nil (staticcheck)
  Error: SA5011: possible nil pointer dereference (staticcheck)
  Error: SA5011(related information): this check suggests that the pointer can be nil (staticcheck)
  Error: SA5011: possible nil pointer dereference (staticcheck)
  Error: SA5011(related information): this check suggests that the pointer can be nil (staticcheck)
  
  Error: issues found
  Ran golangci-lint in 2016ms

in same time 

```

func (database.DB).GetUserByLogin(login string) *database.User
GetUserByLogin returns user with specified login

returns nil if user not found
```

so golangci fail checks, because configured to fail `return nil` case, from the function which returns nil as result

**Comment by maximihajlov** [comment]
`t.Error` fails the test, but does not stop execution. That's why linter shows, that pointer can be null. Use `t.Fatal` instead.

https://go.dev/play/p/coIUIr1H2cF

**Comment by healingdrawing** [comment]
Solved using replacement of `t.Errorf` with `t.Fatalf`.
