### ISSUE TITLE
Safari issues

### ISSUE THREAD

**Issue by nattikim** [merpw/forum#34]
### Categories
The categories works unstable, sometimes it doesn't let you to choose some of them... and seems like it is only on mobile   

<img width="1128" alt="Screen Shot 2023-05-31 at 16 17 31" src="https://github.com/merpw/forum/assets/93912586/eb203b66-0b2d-44de-9ac0-0e87ceb864dc">

**Comment by bomanviktor** [comment]
What was the issue? Is it still ongoing?

**Comment by nattikim** [comment]
@bomanviktor I have edited the issue 👆🏻

**Comment by maximihajlov** [comment]
> are you sure you don't have this issue on your mobile?

@nattikim, I never had such issue. As I understand, it exists only in Safari (on both iOS and MacOS). Does it still exist for you?

The solution can be to replace this react-select component with something more stable (preferably with tailwindcss integration)
