### ISSUE TITLE
Username Space issue

### ISSUE THREAD

**Issue by nattikim** [merpw/forum#36]
There is an issue in Login form, Username/email field

<img width="707" alt="Screen Shot 2023-04-25 at 23 45 04" src="https://user-images.githubusercontent.com/93912586/234399593-571c4121-980b-4d5f-837a-a53469a05638.png">

It is possible to add Space only in already typed in word (first type "SpaceIssue", then move to the middle of the word and add Space)

**Comment by healingdrawing** [comment]
@nattikim and where is issue?
if user can not register his account using username with space inside, it is not an issue.
if after registering(using credentials without space) user trying to type space in login form, inside the username or email field, he is an idiot, and this is his way, it is not an issue of the login form.

do i understand something wrong?

**Comment by nattikim** [comment]
*I'll rename the issue to Username issue

**Comment by healingdrawing** [comment]
then looks like it is an issue

**Comment by nattikim** [comment]
- [ ] add new Migration **\***
- [ ] apply Trim to Username Signup form

_\* replace Spaces to "\_" in all existing double usernames (fe Black Cat -> Black_Cat)._

**Comment by bomanviktor** [comment]
Why not allow spaces inside of names?

**Comment by bomanviktor** [comment]
Got it, makes sense. Thanks for the answer

**Comment by sagarishere** [comment]
to provide a simple experience, we should clearly manage the expectations of the user. if I am able to put my username as "sagar yadav", it might be cool to do either of the two things, either to indicate to the user that it is not allowed to use spaces, or to make it clear that spaces will be wiped out, in which case "sagar yadav" and "sa ga rya dav" are equal.

In my opinion, for the audit, we can indicate to the user that spaces are not allowed in the username. A very straightforward approach.

**Comment by bomanviktor** [comment]
@sagarishere It can be checked already in the front. But the user can still send a request directly to the server using curl for example:

https://linuxize.com/post/curl-post-request/

**Comment by sagarishere** [comment]
that's a single line check 
`validUserName := regexp.MustCompile(`^[a-zA-Z0-9]{6,15}$`)`

**Comment by bomanviktor** [comment]
Yup, it is a better solution even since we can get consistency in the front and the back.

However, should be written:  ```^\w{3,15}$``` as underscores are allowed in the username.
