### ISSUE TITLE
Vanilla Frontend

### ISSUE THREAD

**Issue by bomanviktor** [merpw/forum#51]
All base functionality is completed. Got a perfect score on lighthouse tests;
![lighthouse100](https://github.com/merpw/forum/assets/72476579/846c51ba-3772-4c4f-9365-98e40df414ba)

I am waiting on consensus on how all websocket-related data will be organized and sent to the front before I keep working.

Meanwhile I will:
- [ ] Implement basic websockets on vanilla
- [ ] Further optimize for mobile devices
- [x] Improve and refactor CSS

I could also help with backend either with testing or with working on the websockets.

**Comment by maximihajlov** [comment]
Resolved by #81
