### ISSUE TITLE
Lazy loading

### ISSUE THREAD

**Issue by maximihajlov** [merpw/forum#52]
There's no lazy loading for `PostList` and `Comments`, which causes performance issues, when amount of posts/comments is more than 50.

To solve this we can: 

- [ ] Implement `limit` and `offset` url query parameters for `/api/posts` and `/api/posts/{id}/comments`

**OR**

- [ ] Change endpoints to return array of ids instead of full post/comment data to fetch this data making individual requests (and implement `/api/posts/{id}/comments/{id}`). Like we do for chats and messages. 

And:
- [ ] Update components to lazy-load new posts and comments

**Comment by maximihajlov** [comment]
> Oh, I forgot this in my review of backend refactoring. Could this be implemented in next version?

This pull request was just a refactoring of the existing code. Lazy loading is a completely different feature that should be a subject of another pull request.

> Or do we ignore this and do this for Social Network?

Lazy loading is required for chats in `real-time-forum`. I think it makes sense to implement it for chats and messages first, and continue with posts and comments later in `social-network`.

**Comment by bomanviktor** [comment]
> Lazy loading is required for chats in real-time-forum. I think it makes sense to implement it for chats and messages first, and continue with posts and comments later in social-network.

Okay! Makes sense. So I can skip frontend logic for lazy loading of posts alltogether then.

**Comment by bomanviktor** [comment]
Sorry for closing this issue as well, I assumed it was about the chats based of the title. My bad
