### ISSUE TITLE
Change content and name length in backend

### ISSUE THREAD

**Issue by bomanviktor** [merpw/forum#66]
I see inconsistencies in having very "harsh" restrictions on names in backend, and being very "generous" about content length of comments and posts:
![image](https://github.com/merpw/forum/assets/72476579/36846d31-0c49-4570-89b3-3cc4aec5821d)
![image](https://github.com/merpw/forum/assets/72476579/53386d1b-1b24-4aa7-81ae-95e994cdb794)
![image](https://github.com/merpw/forum/assets/72476579/921166ac-afaa-4544-95d9-d1ebefee1f9c)

My suggestions:
- [ ]  Cut content of posts in half, from 10000 to 5000 characters.
- [ ]  Cut content of comments in half, from 1000 to 500 characters.
- [ ]  Increase length of names (excluding username) from 15 to 30.
    Long last name that would be excluded from forum: https://en.wikipedia.org/wiki/Sotirios_Papagiannopoulos
    Also take into consideration double-barreled names: https://en.wikipedia.org/wiki/Double-barrelled_name
- [ ]  Add password regex to require uppercase character and a numerical character.

What do you think? @nattikim @maximihajlov

**Comment by maximihajlov** [comment]
> * [ ]   Cut content of posts in half, from 10000 to 5000 characters.
> * [ ]   Cut content of comments in half, from 1000 to 500 characters.

Why? We don't have any problems with storing more content. Existing 10k and 1k seem fair to me. 

> * [ ]   Increase length of names (excluding username) from 15 to 30.

That's fair. I think it make sense to use one of the existing standards. 
https://www.ibm.com/docs/en/sva/9.0.2.1?topic=configuration-maximum-lengths-names-by-user-registry

We can use `optimal length` values from this specification. E.g. 64 chars for First and Last names. But if we start worrying about long names users, we should also handle such cases:

![image](https://github.com/merpw/forum/assets/43277901/74e80955-d54b-4775-b668-664b8daf4c1d)

We're going to show full name for contacts in the chat list, so for this change we also have to define the behavior if the name is too long to be displayed. 

![image](https://github.com/merpw/forum/assets/43277901/6b9d6efc-7a31-4f2c-a28a-800a53c97039)

> * [ ]   Add password regex to require uppercase character and a numerical character.

I think there's no need to restrict freedom of users to select any passwords they want. Something like `Password1` will pass this security check, even though it's much less secure than `這些柔軟的法式麵包還有誰`, which doesn't.

**Comment by nattikim** [comment]
Username shouldn't be too long, that's for sure. 15 is enough (it can be increased up to 18-19 max)

<img width="286" alt="Screenshot 2023-06-18 at 19 58 36" src="https://github.com/merpw/forum/assets/93912586/c1315f39-41f8-4da0-98a3-1d514daa6f66">

<br/>
<br/>
<br/>

> https://www.ibm.com/docs/en/sva/9.0.2.1?topic=configuration-maximum-lengths-names-by-user-registry
> We can use the `optimal length` values from this specification. E.g. 64 chars for first and last names.

I think it talks about the longest names. There is always rare cases, such as very long names, or no surname at all etc so I think it's better to stick to an average cases. 30 symbols would be enough 👍🏻
<br/>

> We're going to show full name for contacts in the chat list, so for this change we also have to define the behavior if the name is too long to be displayed.

Why not just to use Username??? 🤔 
As I remember we are hiding personal info from the users we don't follow, but we can chat with any of users even if we don't follow each other.. so by idea full name (as personal info) shouldn't be seen..
<br/>

> Cut content of posts in half, from 10000 to 5000 characters.
> Cut content of comments in half, from 1000 to 500 characters.

Yeah I see no reason to cut Content length for now.. 🤔
Maybe with comments it would be somehow reasonable? Like to prevent spamming with very long comments... to scroll less between comments... Posts are safe in this sense, coz its description is limited by 200 symbols or so..
Still not sure if it needed... what do you think?
