### ISSUE TITLE
Add avatar and about me fields to the sign up form

### ISSUE THREAD

**Issue by maximihajlov** [merpw/forum#93]
Add two new fields to the registration form: `avatar` and `bio`

Uploading of the avatars is not a requirement, so in the initial implementation we will pre-define them. They will be served by the frontend. We will have 10 different avatars with filenames `0.jpg`, `1.jpg` ... `9.jpg`

### Backend

Both new fields are optional strings. To store them in the database a new migration should be implemented. This change is very similar to adding new signup fields in #14. The type of new fields in models will be `sql.NullString`. 

Backend should check if avatar exists during sign up (matches `0..9.jpg`).

`bio` should have the same length limit as the post descriptions. 

This fields should be added to `/api/me` response to be able to see them on the profile page. 

Both `avatar` and `bio` fields are public and should be added to the `/api/users/{id}` response.

The tests should be updated to keep the coverage high.

### Frontend

Frontend will serve avatars, they will be stored as files in the `public` directory. 

The design of choosing avatars will look something like this: 

![Image](https://user-images.githubusercontent.com/43277901/257357095-2b6b8c10-1a49-4dd3-9531-c8ca4d73f7bb.png)

During the sign up user can choose one of the avatars and add it as a name (e.g. `0.jpg`) to the signup request. `About me` field is like a post description. 

The `bio` should be shown on `/me` and `/user/{id}`. Avatar component should be updated.

**Comment by maximihajlov** [comment]
Frontend logic is done, I've just pushed it to the linked branch [`features/93-add-avatar-and-bio`](https://github.com/merpw/forum/tree/features/93-add-avatar-and-bio) and tested it with dummy data. 

Design will be improved by @nattikim later. Temporary kittens also are going to be replaced. But the new fields are here:

https://github.com/merpw/forum/assets/43277901/68e13782-d5b2-46ad-9929-c804b54ae2bf

I've also added `About me` to user profiles (`/me` and `/user/{id}`). Now the forum is much more colorful! I also think it would be great to assign random avatars to the users during the migration.

![image](https://github.com/merpw/forum/assets/43277901/3a7699bf-6bb3-4547-9dac-0ceced36c2be)

![image](https://github.com/merpw/forum/assets/43277901/082da470-d8e6-4dea-bd14-fba7de20ed9e)

**Comment by maximihajlov** [comment]
Hey @FinnTune @bomanviktor. Any updates on the backend?

**Comment by FinnTune** [comment]
I believe I've added everything, but I'm not sure how to add the tests.
Never done it before.

**Comment by maximihajlov** [comment]
One more thing. `username` should be optional in the `social-network`

I've updated the frontend in 5a871d7d253b130d45315e8bf74303b6ef4a7227, so now it looks like this:

![image](https://github.com/merpw/forum/assets/43277901/4ccb18e4-e104-4555-abcb-d6d04d1a7765)

If the username is not specified, an automatic `u123456` should be used on the backend (where 123456 is user id). I think `u123456`  format is good choice because we already have `u123456` in chats (`/chat/u123456`)

We should also restrict providing `u123456` as a username to prevent cases when the username was already taken by someone else.

**Comment by bomanviktor** [comment]
Backend logic should be done. I added tests to go with it so that the coverage stays the same.

**Comment by nattikim** [comment]
The avatar is visible only to the owner


![Image](https://github.com/merpw/forum/assets/93912586/96da8510-bee2-4433-8ad8-e9c3e43b5d16)



![Image](https://github.com/merpw/forum/assets/93912586/a6984c74-9269-4703-a132-730f46d00153)

**Comment by maximihajlov** [comment]
> The avatar is visible only to the owner

Good catch, fea062c1e472e8cfd8210a0230644b4356e01c7a fixes this

**Comment by nattikim** [comment]
Would be cool to make the avatars layout like so ↓

<img width="1370" alt="Screen Shot 2023-08-03 at 18 09 10" src="https://github.com/merpw/forum/assets/93912586/e65146d9-3520-4ed0-9566-2b6d429ecfc3">
<br></br>
It'll save some space and it will look much neater ✨

Also, would be nice if it'll be something like closed circle, when last pic followed by first pic 🔄

**Comment by nattikim** [comment]
Please welcome our new avatars

<img width="563" alt="Screen Shot 2023-08-04 at 00 26 29" src="https://github.com/merpw/forum/assets/93912586/76b7cdb5-a9b1-480c-a9fd-79d0212ae127">

My original idea, when we just started with the forum, was to have a hacker cat as a "mascot".. I also added some other animals here for variety but the theme stays the same.. hacker cat/other animal and cyber style 🧑‍💻

**Comment by FinnTune** [comment]
I love them)

**Comment by maximihajlov** [comment]
> Would be cool to make the avatars layout like so ↓

Implementation of this layout looks quite complicated to me. There's no native way to implement infinite scroll loop in HTML. The only way to do this is to manually remove some elements from the beginning and add them to the end. But it's not compatible with css scroll snap, so it's not stable for our case.

As it's not a requirement I think it's better to concentrate on the mandatory features and implement design improvements if we have some time later. 

Avatar looks great to me, so you can push them so we can merge #98

**Comment by bomanviktor** [comment]
I agree with Max, just make sure the avatars are centered! Looked kinda wonky before with the cat avatars.
