### ISSUE TITLE
Add followers and profile privacy modes

### ISSUE THREAD

**Issue by maximihajlov** [merpw/forum#94]
## Backend

- [x] Add public mode

A new integer field `privacy` should be added to the `users` column. It can be `0` if profile is public or `1` if it's private. All existing users should have `1` as a default value. 

This field should be added to `/api/me` endpoint as bool. 

A new `POST /api/me/privacy` endpoint should be implemented. It should toggle privacy mode (similar to likes). It should return current privacy ("true" or "false")

Handler `/user/{id}` should be updated to send full name, date of birth and gender if the profile is public. 

- [x] Add followers. 

A new table `followers` should be added to the main database. It should be similar to the table `memberships` in chat database and contain several fields: primary key `id`, foreign key `user_id`, foreign key `follower_id` and a timestamp. 

The `followStatus` field should be added to `/users/{id}`. It can have three states (0-not following, 1-following, 2-requested to follow)

A new `/users/{id}/follow` endpoint should be implemented. It should toggle following of the user (similar to likes). It should return the `followStatus` (0, 1 or 2).

> Only for public profiles for now, private profiles require invitations #95 

This issue does not include post privacy, so all posts of users will remain public (and will be available to anyone).  

## Frontend

The `/user/{id}` page should be updated to render on client side. Right now it's server-side rendered, but since the profiles can be private, server will not have access to private fields of users. SWR fallback should be used for mutating data on client side. Like we already do for comments: 

https://github.com/merpw/forum/blob/db646fc8044cd55b5f9f11aa9e06537395872da9/frontend/src/app/post/%5Bid%5D/Comments.tsx#L12-L24

Follow button should be implemented. There should be indication if the user is followed or not. There should be a confirmation popup if you want to unfollow the user.

**Comment by maximihajlov** [comment]
Basic version of the frontend is done. I've just pushed it to the linked branch [features/94-add-followers-and-profile-privacy](https://github.com/merpw/forum/tree/features/94-add-followers-and-profile-privacy). It's not perfect, but it's good enough to start doing backend. The design will be improved by @nattikim later. 

Two new fields were added to `User` type:

```ts
export type User = {
  // old fields...

  privacy?: boolean
  followStatus?: FollowStatus
}

/** 0 - not following, 1 - following, 2 - requested */
export type FollowStatus = 0 | 1 | 2 
```

Users can now toggle privacy mode on `/me`:

https://github.com/merpw/forum/assets/43277901/437808af-90bc-4b4a-86f8-ed1adb83efd6

On each toggle change, a `POST /api/me/privacy` request is sent.

Public profiles now look like this:

![image](https://github.com/merpw/forum/assets/43277901/cb4cdc92-3d1b-41e2-a56f-b9e6b86d4f1f)

And private:

![image](https://github.com/merpw/forum/assets/43277901/ee164bfc-0376-4530-a93c-0f75159b572d)

When clicking the `Follow` button, a `POST /api/users/{id}/follow` request is sent. And depending on the return value, the button text changes:

to `Unfollow` for public

![image](https://github.com/merpw/forum/assets/43277901/b7b05a65-b960-4691-8e92-1ba3d946bc79)

to `Cancel request` for private

![image](https://github.com/merpw/forum/assets/43277901/6d801b7a-a80b-4273-803b-6dbeb237d351)

There's also a confirmation popup when clicking `Unfollow` or `Cancel request`, which is a bonus:

![image](https://github.com/merpw/forum/assets/43277901/1361dad9-24e3-4029-91ea-f4510c45c3be)

Let me know if I missed something. Looking forward to test it with the real backend 👀.

**Comment by bomanviktor** [comment]
Awesome stuff! Getting to work on the backend now.

**Comment by maximihajlov** [comment]
@bomanviktor, I've started working on private posts frontend and see that we also need `/api/me/followers` endpoint, which will return all authenticated user's followers (as array of ids), to be able to select audience of the super-private post. 

We can include it into this issue or handle it in #99.
